apiVersion: v1
kind: Service
metadata:
  name: kafka-neo4j-connector
spec:
  selector:
    app: kafka-neo4j-connector
  ports:
    - name: connector-rest
      protocol: TCP
      port: 8083
      targetPort: 8083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-neo4j-connector
  labels:
    app: kafka-neo4j-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-neo4j-connector
  template:
    metadata:
      labels:
        app: kafka-neo4j-connector
    spec:
      containers:
        - name: kafka-neo4j-connector
          image: roy012299/kafka-neo4j-connect:latest          
          #command: ["/bin/bash", "-c", "cd /home/appuser && ./init.sh && sleep infinity"]
          ports:
            - containerPort: 8083
          env:
            - name: CONNECT_BOOTSTRAP_SERVERS
              value: kafka-service:29092
            - name: CONNECT_REST_PORT
              value: "8083"
            - name: CONNECT_GROUP_ID
              value: kafka-neo4j-connector-group
            - name: CONNECT_CONFIG_STORAGE_TOPIC
              value: "connect-configs"
            - name: CONNECT_OFFSET_STORAGE_TOPIC
              value: "connect-offsets"
            - name: CONNECT_STATUS_STORAGE_TOPIC
              value: "connect-statuses"
            - name: CONNECT_PLUGIN_PATH
              value: "/usr/share/java,/usr/share/confluent-hub-components"
            - name: CONNECT_NEO4J_URI
              value: "bolt://neo4j-service:7687"
            - name: CONNECT_NEO4J_USER
              value: "neo4j"
            - name: CONNECT_NEO4J_PASSWORD
              value: "project1phase2"
